'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'en' | 'vi';

// ── Translations ──────────────────────────────────────────────────────────────
const translations = {
  en: {
    // Nav
    signIn: 'Sign In',
    getStartedFree: 'Get Started Free',

    // Landing hero
    heroTitle: 'Detect Product Defects\nInstantly with AI',
    heroSubtitle:
      'Upload an image. Get instant AI-powered defect analysis. Built for manufacturers, QA teams, and quality engineers who demand precision.',
    startFree: 'Start for Free →',
    badgeLabel: '✨ AI-Powered Quality Inspection',

    // Stats
    statAccuracy: 'Detection Accuracy',
    statSpeed: 'Analysis Time',
    statClasses: 'Defect Classes',

    // Features section
    featuresTitle: 'Everything you need for quality control',
    features: [
      { icon: '⚡', title: 'Instant Analysis', desc: 'Get defect classification results in under 200ms with our optimized inference pipeline.' },
      { icon: '🎯', title: '6 Defect Classes', desc: 'Detect scratches, dents, cracks, contamination, missing parts, and good products.' },
      { icon: '📊', title: 'Analytics Dashboard', desc: 'Track your inspection history, usage stats, and defect trends over time.' },
      { icon: '🔒', title: 'Secure & Private', desc: 'Images are processed securely with JWT authentication and never stored permanently.' },
      { icon: '💳', title: 'Flexible Plans', desc: 'Start free with 50 inspections/month. Upgrade to Pro for unlimited access.' },
      { icon: '🚀', title: 'API Access', desc: 'Integrate directly with your production systems via our REST API.' },
    ],

    // Pricing
    pricingTitle: 'Simple, transparent pricing',
    pricingSubtitle: 'No hidden fees. No credit card required to start.',
    forever: 'forever',
    perMonth: 'per month',
    getStarted: 'Get Started',
    startProTrial: 'Start Pro Trial',
    freePlanFeatures: ['50 inspections/month', 'All 6 defect classes', 'Basic history (7 days)', 'Email support'],
    proPlanFeatures: ['Unlimited inspections', 'All 6 defect classes', '90-day history', 'REST API access', 'Priority queue', 'Priority support'],

    // Defect Labels
    defects: {
      good: 'Good (No Defect)',
      scratch: 'Scratch',
      dent: 'Dent',
      crack: 'Crack',
      contamination: 'Contamination',
      missing_part: 'Missing Part',
    },

    // Footer
    footerText: '© 2024 VisionInspect. Built with ❤️ using PyTorch + FastAPI + Next.js',

    // Auth
    welcomeBack: 'Welcome back',
    signInToAccount: 'Sign in to your account',
    emailAddress: 'Email address',
    password: 'Password',
    enterPassword: 'Enter your password',
    signingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    signUpFree: 'Sign up free',

    createAccount: 'Create your account',
    startDetecting: 'Start detecting defects for free',
    fullName: 'Full name',
    confirmPassword: 'Confirm password',
    repeatPassword: 'Repeat your password',
    creatingAccount: 'Creating account...',
    createFreeAccount: 'Create Free Account',
    alreadyAccount: 'Already have an account?',
    termsNote: 'By signing up you agree to our Terms of Service and Privacy Policy.',

    // Dashboard sidebar
    dashboard: 'Dashboard',
    inspectImage: 'Inspect Image',
    history: 'History',
    usagePlan: 'Usage & Plan',
    upgradeToPro: 'Upgrade to Pro',
    realtimeMonitor: 'Real-time Monitor',
    adminPanel: 'Admin Panel',
    datasetManager: 'Dataset Manager',
    aiTraining: 'AI Training',
    modelRegistry: 'Model Registry',
    trainingHistory: 'Training History',
    loadingWorkspace: 'Preparing your workspace...',
    realtimeTitle: 'AI Inspection Control Center',
    realtimeSubtitle: 'Live System Monitoring — Production Line #1',
    localTime: 'Local Time',
    aiEngineActive: 'AI ENGINE: ACTIVE',
    cameraActiveLabel: 'CAM',
    startInspection: 'Start Inspection',
    pauseTracking: 'Pause Tracking',
    cameraSettings: 'Camera Settings',
    resetCounters: 'Reset Counters',
    liveInspectionLog: 'Live Inspection Log',
    realtime: 'Real-time',
    waitingDetections: 'Waiting for new detections...',
    viewFullHistory: 'View Full History',
    lineEfficiency: 'Line Efficiency',
    targetAchievement: 'Target Achievement',
    lineSpeedOptimal: 'Line speed is currently optimal. Defect rate is within acceptable 2% threshold.',
    cameraConfig: 'Camera Configuration',
    connectionType: 'Connection Type',
    ipRtspAddress: 'RTSP/HTTP URL Address',
    bluetoothNote: 'Note: Bluetooth cameras require bridge software to export an RTSP stream. Enter the RTSP URL in WiFi mode after connecting.',
    saveConfig: 'Save Configuration',
    connectNewSourceSuccess: 'New camera source connected!',
    connectSourceError: 'Could not connect to this camera source.',
    serverError: 'Server connection error.',
    enterIpRtsp: 'Please enter IP/RTSP address',
    restartingBackend: 'Camera updated. Please restart Backend to apply.',
    backToAdminHub: 'Back to Admin Hub',
    datasetManagerTitle: 'Dataset Manager',
    datasetManagerSubtitle: 'Upload images, YOLO labels, ZIP datasets, manage splits, and inspect live statistics.',
    datasetsLabel: 'Datasets',
    assetsLabel: 'Assets',
    classesLabel: 'Classes',
    createDatasetProject: 'Create dataset project',
    datasetNamePlaceholder: 'Dataset name',
    optionalSlug: 'Optional slug',
    datasetDescriptionPlaceholder: 'Dataset description',
    classesPlaceholder: 'Classes separated by commas',
    creating: 'Creating...',
    createDatasetBtn: 'Create Dataset',
    uploadAndSplit: 'Upload & Split',
    dropFilesHere: 'Drop files here',
    dragDropOrClick: 'Drag & drop or click to select files',
    uploading: 'Uploading...',
    uploadToDataset: 'Upload to dataset',
    recomputeSplit: 'Recompute split',
    largeUploadSupport: 'Supports large drag & drop uploads.',
    totalImages: 'Total images',
    totalLabels: 'Total labels',
    trainValTest: 'Train/Val/Test',
    datasetList: 'Dataset list',
    selectDatasetToInspect: 'Select a dataset to inspect assets and previews.',
    noDescription: 'No description yet',
    rename: 'Rename',
    delete: 'Delete',
    assetPreview: 'Asset preview',
    noDatasetSelected: 'No dataset selected',
    defectDistribution: 'Defect distribution',
    datasetStorageNote: 'Datasets are stored under storage/datasets/<slug> with split-based images/ and labels/ folders.',
    allAssets: 'All Assets',
    loadDatasetError: 'Failed to load datasets',
    enterDatasetName: 'Enter a dataset name',
    datasetCreated: 'Dataset created',
    failedCreateDataset: 'Failed to create dataset',
    selectDatasetAndFile: 'Select a dataset and at least one file',
    filesUploaded: 'Files uploaded',
    uploadFailed: 'Upload failed',
    newDatasetName: 'New dataset name',
    datasetRenamed: 'Dataset renamed',
    renameFailed: 'Rename failed',
    deleteDatasetConfirm: 'Delete this dataset?',
    deleteAssetConfirm: 'Are you sure you want to delete this file from the dataset?',
    datasetDeleted: 'Dataset deleted',
    assetDeleted: 'File deleted successfully',
    deleteFailed: 'Delete failed',
    deleteAssetFailed: 'Failed to delete file',
    splitUpdated: 'Split updated',
    failedSplitDataset: 'Failed to split dataset',
    loadTrainingDataError: 'Failed to load training data',
    monitoringSocketError: 'Monitoring socket error',
    selectDataset: 'Select dataset',
    jobQueued: 'Training job queued',
    unableStartTraining: 'Unable to start training',
    aiTrainingTitle: 'AI Training',
    aiTrainingSubtitle: 'Configure YOLOv8, queue jobs to Redis, and follow epoch/loss/mAP in realtime.',
    startTrainingLabel: 'Start Training',
    trainingJobNote: 'Jobs are queued into Redis and processed by a dedicated worker. A model version is created automatically when training completes.',
    recentJobs: 'Recent jobs',
    detectionQuality: 'Detection quality',
    trainingLoss: 'Training loss',
    remainingTime: 'Remaining time',
    progress: 'Progress',
    precision: 'Precision',
    recall: 'Recall',
    trainingLogs: 'Training logs',
    selectRunningJob: 'Select a running job to stream realtime logs.',
    workerNote: 'Worker publishes epoch status to Supabase. This websocket monitors live updates without refresh.',
    billingUsage: 'Usage & Billing',
    billingSubtitle: 'Choose the right plan for your production needs.',
    usageProgress: 'Usage Progress',
    predictionsUsed: 'Predictions Used',
    resetNotice: 'Limit will automatically reset at the beginning of next month.',
    paymentMethods: 'Payment Methods',
    noPaymentMethod: 'No payment methods connected.',
    addPayment: 'Add new method +',
    billingHistory: 'Billing History',
    noBillingHistory: 'No transactions found.',
    viewAll: 'View All',
    using: 'In Use',
    upgradeDesc: 'Unlimited inspections + API access',
    upgradeNow: 'Upgrade Now',
    signOut: 'Sign Out',
    freePlan: '✓ Free Plan',
    proPlan: '⭐ Pro Plan',

    // Dashboard home
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Your inspection overview at a glance',
    totalInspections: 'Total Inspections',
    thisMonth: 'This Month',
    avgConfidence: 'Avg. Confidence',
    mostCommonDefect: 'Most Common Defect',
    monthlyUsage: 'Monthly Usage',
    unlimited: 'Unlimited — Pro Plan',
    inspectionsUsed: 'inspections used',
    usageWarning: 'inspections remaining',
    fromLastMonth: 'from last month',
    remainingLabel: 'Remaining',
    inThisMonth: 'in this month',
    upgradeProDesc: 'Upgrade to Pro for unlimited inspections and advanced AI models.',
    upgradeNowLabel: 'Upgrade Now →',
    loadingDashboard: 'Loading dashboard...',
    newInspection: 'New Inspection',
    newInspectionDesc: 'Upload an image to analyze',
    viewHistory: 'View History',
    viewHistoryDesc: 'Browse past inspections',
    defectBreakdown: 'Defect Breakdown',
    noInspections: 'No inspections yet',
    noInspectionsDesc: 'Upload your first product image to get started',
    startFirstInspection: 'Start First Inspection',
    resets: 'Resets',
    uploadMode: 'Upload',
    cameraMode: 'Camera',
    streamMode: 'Live Stream',
    takePhotoNow: 'TAKE PHOTO NOW',
    captureFromStream: 'CAPTURE FROM STREAM',
    startInspectionBtn: 'START INSPECTION',
    analyzingBtn: 'Analyzing...',
    capturedSuccess: 'Captured!',
    frameCaptured: 'Frame Captured',
    retakeBtn: 'Retake',
    analysisComplete: 'Analysis complete!',
    analysisFailed: 'Analysis failed. Please try again.',
    visualInspection: 'Visual Inspection',
    totalLabel: 'Total',
    goodLabel: 'Good',
    defectLabel: 'Defect',
    liveStatus: 'Live',
    offlineStatus: 'Offline',
    zoomInLabel: 'Zoom In',
    zoomOutLabel: 'Zoom Out',
    resetZoomLabel: 'Reset Zoom',
    zoomLevelLabel: 'Zoom',
    analysisResult: 'Analysis Result',

    confidence: 'Confidence',
    processingTime: 'Processing Time',
    detailScores: 'Detailed Scores',
    aiSurfaceDetection: 'Use AI to detect surface defects in seconds.',
    perfectSurface: 'Perfect Surface',
    anomalyDetected: 'Anomaly Detected',
    perfectDesc: 'No signs of damage or surface defects detected on this object.',
    anomalyDesc: 'The system has detected inconsistencies. Please check manually.',

    // Inspect page
    inspectTitle: 'Inspect Image',
    inspectSubtitle: 'Upload a product image to detect defects using AI',
    dropImageOrBrowse: 'Drop an image or click to browse',
    dropHere: 'Drop it here',
    fileFormats: 'JPEG, PNG, WEBP · Max 10MB',
    analyzeImage: '🔍 Analyze Image',
    analyzing: 'Analyzing...',
    reset: 'Reset',
    resultsAppearHere: 'Analysis results will appear here',
    runningAI: 'Running AI analysis...',
    typicallyUnder: 'Typically takes under 200ms',
    noDefectsDetected: 'No defects detected',
    defectDetected: 'Defect detected',
    scoreBreakdown: 'SCORE BREAKDOWN',

    // Webcam
    useCamera: 'Use Camera',
    useUpload: 'Upload File',
    capture: 'Capture & Analyze',
    retake: 'Retake',
    cameraError: 'Camera access denied or not found',

    // History page
    historyTitle: 'Inspection History',
    totalInspectionsLabel: 'total inspections',
    loading: 'Loading...',
    file: 'File',
    result: 'Result',
    speed: 'Speed',
    date: 'Date',
    prev: '← Prev',
    next: 'Next →',
    page: 'Page',
    of: 'of',
    noHistory: 'No history yet',
    noHistoryDesc: 'Run your first inspection to see results here',
    startInspecting: 'Start Inspecting',

    // Usage page
    usageTitle: 'Usage & Plan',
    usageSubtitle: 'Manage your subscription and track your usage',
    thisMonthsUsage: "This Month's Usage",
    currentPlan: 'Current Plan',
    unlimitedInspections: '✓ Unlimited inspections',
    resetsOn: 'Resets on',
    cancels: 'Cancels on',
    renews: 'Renews on',
    cancelWarning: '⚠️ Your subscription will cancel at the end of this billing period',
    upgradeBtnLabel: '⭐ Upgrade to Pro — $29/mo',
    redirecting: 'Redirecting...',
    cancelSubscription: 'Cancel Subscription',
    canceling: 'Canceling...',
    remaining: 'remaining',
    percentUsed: 'used',
    planComparison: 'Plan Comparison',
    feature: 'Feature',
    free: 'Free',
    pro: 'Pro',
    planRows: [
      { feature: 'Inspections / month', free: '50', pro: 'Unlimited' },
      { feature: 'History retention', free: '7 days', pro: '90 days' },
      { feature: 'REST API access', free: '✗', pro: '✓' },
      { feature: 'Priority queue', free: '✗', pro: '✓' },
      { feature: 'Priority support', free: '✗', pro: '✓' },
      { feature: 'Price', free: '$0/mo', pro: '$29/mo' },
    ],
  },

  vi: {
    // Nav
    signIn: 'Đăng Nhập',
    getStartedFree: 'Dùng Miễn Phí',

    // Landing hero
    heroTitle: 'Phát Hiện Lỗi Sản Phẩm\nTức Thì Bằng AI',
    heroSubtitle:
      'Tải ảnh lên. Nhận phân tích lỗi bằng AI ngay lập tức. Được xây dựng cho nhà sản xuất, nhóm QA và kỹ sư chất lượng.',
    startFree: 'Bắt đầu miễn phí →',
    badgeLabel: '✨ Kiểm Tra Chất Lượng Bằng AI',

    // Stats
    statAccuracy: 'Độ Chính Xác',
    statSpeed: 'Thời Gian Phân Tích',
    statClasses: 'Loại Lỗi',

    // Features section
    featuresTitle: 'Tất cả những gì bạn cần để kiểm soát chất lượng',
    features: [
      { icon: '⚡', title: 'Phân Tích Tức Thì', desc: 'Nhận kết quả phân loại lỗi trong vòng 200ms với quy trình suy luận tối ưu.' },
      { icon: '🎯', title: '6 Loại Lỗi', desc: 'Phát hiện trầy xước, móp méo, vết nứt, nhiễm bẩn, thiếu linh kiện và sản phẩm tốt.' },
      { icon: '📊', title: 'Bảng Điều Khiển Phân Tích', desc: 'Theo dõi lịch sử kiểm tra, thống kê sử dụng và xu hướng lỗi theo thời gian.' },
      { icon: '🔒', title: 'Bảo Mật & Riêng Tư', desc: 'Hình ảnh được xử lý an toàn với xác thực JWT và không được lưu trữ vĩnh viễn.' },
      { icon: '💳', title: 'Gói Linh Hoạt', desc: 'Bắt đầu miễn phí với 50 lần kiểm tra/tháng. Nâng cấp lên Pro để sử dụng không giới hạn.' },
      { icon: '🚀', title: 'Truy Cập API', desc: 'Tích hợp trực tiếp với hệ thống sản xuất của bạn qua REST API.' },
    ],

    // Pricing
    pricingTitle: 'Bảng giá đơn giản, minh bạch',
    pricingSubtitle: 'Không phí ẩn. Không cần thẻ tín dụng để bắt đầu.',
    forever: 'mãi mãi',
    perMonth: 'mỗi tháng',
    getStarted: 'Bắt Đầu',
    startProTrial: 'Dùng Thử Pro',
    freePlanFeatures: ['50 lần kiểm tra/tháng', 'Đủ 6 loại lỗi', 'Lịch sử cơ bản (7 ngày)', 'Hỗ trợ qua email'],
    proPlanFeatures: ['Không giới hạn kiểm tra', 'Đủ 6 loại lỗi', 'Lịch sử 90 ngày', 'Truy cập REST API', 'Hàng đợi ưu tiên', 'Hỗ trợ ưu tiên'],

    // Defect Labels
    defects: {
      good: 'Sản phẩm tốt',
      scratch: 'Trầy xước',
      dent: 'Móp méo',
      crack: 'Vết nứt',
      contamination: 'Nhiễm bẩn',
      missing_part: 'Thiếu linh kiện',
    },

    // Footer
    footerText: '© 2024 VisionInspect. Xây dựng với ❤️ bằng PyTorch + FastAPI + Next.js',

    // Auth
    welcomeBack: 'Chào mừng trở lại',
    signInToAccount: 'Đăng nhập vào tài khoản của bạn',
    emailAddress: 'Địa chỉ email',
    password: 'Mật khẩu',
    enterPassword: 'Nhập mật khẩu',
    signingIn: 'Đang đăng nhập...',
    noAccount: 'Chưa có tài khoản?',
    signUpFree: 'Đăng ký miễn phí',

    createAccount: 'Tạo tài khoản',
    startDetecting: 'Bắt đầu phát hiện lỗi miễn phí',
    fullName: 'Họ và tên',
    confirmPassword: 'Xác nhận mật khẩu',
    repeatPassword: 'Nhập lại mật khẩu',
    creatingAccount: 'Đang tạo tài khoản...',
    createFreeAccount: 'Tạo Tài Khoản Miễn Phí',
    alreadyAccount: 'Đã có tài khoản?',
    termsNote: 'Bằng cách đăng ký, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật.',

    // Dashboard sidebar
    dashboard: 'Bảng Điều Khiển',
    inspectImage: 'Kiểm Tra Ảnh',
    history: 'Lịch Sử',
    usagePlan: 'Sử Dụng & Gói',
    upgradeToPro: 'Nâng Cấp Pro',
    realtimeMonitor: 'Giám Sát Trực Tiếp',
    adminPanel: 'Quản trị hệ thống',
    datasetManager: 'Quản lý Dữ liệu',
    aiTraining: 'Huấn luyện AI',
    modelRegistry: 'Kho lưu trữ Model',
    trainingHistory: 'Lịch sử Huấn luyện',
    loadingWorkspace: 'Đang chuẩn bị không gian làm việc...',
    realtimeTitle: 'Trung tâm Giám sát AI',
    realtimeSubtitle: 'Theo dõi hệ thống trực tiếp — Dây chuyền #1',
    localTime: 'Giờ địa phương',
    aiEngineActive: 'AI ENGINE: ĐANG CHẠY',
    cameraActiveLabel: 'CAM',
    startInspection: 'Bắt đầu kiểm tra',
    pauseTracking: 'Tạm dừng theo dõi',
    cameraSettings: 'Cấu hình Camera',
    resetCounters: 'Đặt lại bộ đếm',
    liveInspectionLog: 'Nhật ký kiểm tra trực tiếp',
    realtime: 'Thời gian thực',
    waitingDetections: 'Đang chờ phát hiện mới...',
    viewFullHistory: 'Xem toàn bộ lịch sử',
    lineEfficiency: 'Hiệu suất dây chuyền',
    targetAchievement: 'Mục tiêu đạt được',
    lineSpeedOptimal: 'Tốc độ dây chuyền hiện đang tối ưu. Tỷ lệ lỗi nằm trong ngưỡng cho phép 2%.',
    cameraConfig: 'Cấu hình Camera',
    connectionType: 'Loại kết nối',
    ipRtspAddress: 'Địa chỉ RTSP/HTTP URL',
    bluetoothNote: 'Lưu ý: Camera Bluetooth yêu cầu sử dụng phần mềm bridge để xuất stream RTSP. Hãy nhập URL RTSP vào mục WiFi sau khi kết nối.',
    saveConfig: 'Lưu cấu hình',
    connectNewSourceSuccess: 'Đã kết nối nguồn Camera mới!',
    connectSourceError: 'Không thể kết nối với nguồn Camera này.',
    serverError: 'Lỗi kết nối Server.',
    enterIpRtsp: 'Vui lòng nhập địa chỉ IP/RTSP',
    restartingBackend: 'Đã cập nhật Camera. Vui lòng khởi động lại Backend để áp dụng.',
    backToAdminHub: 'Quay lại Admin Hub',
    datasetManagerTitle: 'Quản lý Dữ liệu',
    datasetManagerSubtitle: 'Upload ảnh, nhãn YOLO, ZIP dataset, chia split và xem thống kê trực tiếp.',
    datasetsLabel: 'Bộ dữ liệu',
    assetsLabel: 'Tệp tin',
    classesLabel: 'Lớp đối tượng',
    createDatasetProject: 'Tạo dự án dataset',
    datasetNamePlaceholder: 'Tên dataset',
    optionalSlug: 'Slug tùy chọn',
    datasetDescriptionPlaceholder: 'Mô tả dataset',
    classesPlaceholder: 'Classes, cách nhau bằng dấu phẩy',
    creating: 'Đang tạo...',
    createDatasetBtn: 'Tạo Dataset',
    uploadAndSplit: 'Tải lên & Phân chia',
    dropFilesHere: 'Thả file tại đây',
    dragDropOrClick: 'Kéo thả file hoặc bấm để chọn',
    uploading: 'Đang tải lên...',
    uploadToDataset: 'Tải lên Dataset',
    recomputeSplit: 'Tính lại phân chia',
    largeUploadSupport: 'Hỗ trợ tải lên lớn qua kéo thả.',
    totalImages: 'Tổng số ảnh',
    totalLabels: 'Tổng số nhãn',
    trainValTest: 'Train/Val/Test',
    datasetList: 'Danh sách bộ dữ liệu',
    selectDatasetToInspect: 'Chọn một bộ dữ liệu để xem chi tiết và xem trước.',
    noDescription: 'Chưa có mô tả',
    rename: 'Đổi tên',
    delete: 'Xóa',
    assetPreview: 'Xem trước tệp',
    noDatasetSelected: 'Chưa chọn bộ dữ liệu',
    defectDistribution: 'Phân phối lỗi',
    datasetStorageNote: 'Bộ dữ liệu được lưu trữ tại storage/datasets/<slug> với các thư mục images/ và labels/ theo từng phần.',
    allAssets: 'Tất cả tệp tin',
    loadDatasetError: 'Không thể tải danh sách bộ dữ liệu',
    enterDatasetName: 'Vui lòng nhập tên bộ dữ liệu',
    datasetCreated: 'Đã tạo bộ dữ liệu',
    failedCreateDataset: 'Tạo bộ dữ liệu thất bại',
    selectDatasetAndFile: 'Vui lòng chọn bộ dữ liệu và ít nhất một tệp',
    filesUploaded: 'Đã tải lên các tệp',
    uploadFailed: 'Tải lên thất bại',
    newDatasetName: 'Tên bộ dữ liệu mới',
    datasetRenamed: 'Đã đổi tên bộ dữ liệu',
    renameFailed: 'Đổi tên thất bại',
    deleteDatasetConfirm: 'Bạn có chắc muốn xóa bộ dữ liệu này?',
    deleteAssetConfirm: 'Bạn có chắc chắn muốn xóa tệp này khỏi bộ dữ liệu không?',
    datasetDeleted: 'Đã xóa bộ dữ liệu',
    assetDeleted: 'Đã xóa tệp thành công!',
    deleteFailed: 'Xóa thất bại',
    deleteAssetFailed: 'Xóa tệp thất bại!',
    splitUpdated: 'Đã cập nhật phân chia',
    failedSplitDataset: 'Phân chia bộ dữ liệu thất bại',
    loadTrainingDataError: 'Không tải được dữ liệu huấn luyện',
    monitoringSocketError: 'Lỗi kết nối giám sát',
    selectDataset: 'Chọn bộ dữ liệu',
    jobQueued: 'Đã đưa yêu cầu vào hàng đợi',
    unableStartTraining: 'Không thể bắt đầu huấn luyện',
    aiTrainingTitle: 'Huấn luyện AI',
    aiTrainingSubtitle: 'Cấu hình YOLOv8, đẩy yêu cầu vào hàng đợi Redis và theo dõi tiến trình trực tiếp.',
    startTrainingLabel: 'Bắt đầu Huấn luyện',
    trainingJobNote: 'Yêu cầu được gửi tới hàng đợi Redis và xử lý bởi worker riêng. Phiên bản model sẽ được tạo tự động sau khi xong.',
    recentJobs: 'Yêu cầu gần đây',
    detectionQuality: 'Độ chính xác nhận diện',
    trainingLoss: 'Độ mất mát huấn luyện',
    remainingTime: 'Thời gian còn lại',
    progress: 'Tiến trình',
    precision: 'Độ chuẩn xác',
    recall: 'Độ bao phủ',
    trainingLogs: 'Nhật ký huấn luyện',
    selectRunningJob: 'Chọn một yêu cầu đang chạy để xem nhật ký trực tiếp.',
    workerNote: 'Worker cập nhật trạng thái vào Supabase. WebSocket này theo dõi trực tiếp mà không cần tải lại trang.',
    billingUsage: 'Gói dịch vụ & Hạn mức',
    billingSubtitle: 'Chọn gói dịch vụ phù hợp với nhu cầu sản xuất của bạn.',
    usageProgress: 'Tiến độ sử dụng',
    predictionsUsed: 'Dự đoán đã dùng',
    resetNotice: 'Hạn mức sẽ tự động reset vào đầu tháng tới.',
    paymentMethods: 'Phương thức thanh toán',
    noPaymentMethod: 'Chưa có phương thức thanh toán nào được kết nối.',
    addPayment: 'Thêm phương thức mới +',
    billingHistory: 'Lịch sử hóa đơn',
    noBillingHistory: 'Chưa có giao dịch nào phát sinh.',
    viewAll: 'Xem tất cả',
    using: 'Đang sử dụng',
    upgradeDesc: 'Không giới hạn kiểm tra + API',
    upgradeNow: 'Nâng Cấp Ngay',
    signOut: 'Đăng Xuất',
    freePlan: '✓ Gói Miễn Phí',
    proPlan: '⭐ Gói Pro',

    // Dashboard home
    dashboardTitle: 'Bảng Điều Khiển',
    dashboardSubtitle: 'Tổng quan kiểm tra của bạn',
    totalInspections: 'Tổng Kiểm Tra',
    thisMonth: 'Tháng Này',
    avgConfidence: 'Độ Chính Xác TB',
    mostCommonDefect: 'Lỗi Phổ Biến Nhất',
    monthlyUsage: 'Sử Dụng Tháng Này',
    unlimited: 'Không Giới Hạn — Gói Pro',
    inspectionsUsed: 'lần đã dùng',
    usageWarning: 'lần còn lại',
    fromLastMonth: 'từ tháng trước',
    remainingLabel: 'Còn lại',
    inThisMonth: 'trong tháng này',
    upgradeProDesc: 'Nâng cấp lên Pro để không giới hạn lượt kiểm tra và sử dụng Model AI nâng cao.',
    upgradeNowLabel: 'Nâng cấp ngay →',
    loadingDashboard: 'Đang tải bảng điều khiển...',
    newInspection: 'Kiểm Tra Mới',
    newInspectionDesc: 'Tải ảnh lên để phân tích',
    viewHistory: 'Xem Lịch Sử',
    viewHistoryDesc: 'Duyệt các kiểm tra trước',
    defectBreakdown: 'Phân Tích Loại Lỗi',
    noInspections: 'Chưa có kiểm tra nào',
    noInspectionsDesc: 'Tải ảnh sản phẩm đầu tiên để bắt đầu',
    startFirstInspection: 'Bắt Đầu Kiểm Tra',
    resets: 'Làm mới',
    uploadMode: 'Tải ảnh',
    cameraMode: 'Camera',
    streamMode: 'Luồng Live',
    takePhotoNow: 'CHỤP ẢNH NGAY',
    captureFromStream: 'CHỤP TỪ LUỒNG LIVE',
    startInspectionBtn: 'BẮT ĐẦU KIỂM TRA',
    analyzingBtn: 'Đang phân tích...',
    capturedSuccess: 'Đã chụp!',
    frameCaptured: 'Đã lấy khung hình',
    retakeBtn: 'Chụp lại',
    analysisComplete: 'Phân tích hoàn tất!',
    analysisFailed: 'Lỗi khi phân tích. Vui lòng thử lại.',
    visualInspection: 'Kiểm tra Trực quan',
    totalLabel: 'Tổng',
    goodLabel: 'Tốt',
    defectLabel: 'Lỗi',
    liveStatus: 'Trực tiếp',
    offlineStatus: 'Ngoại tuyến',
    zoomInLabel: 'Phóng to',
    zoomOutLabel: 'Thu nhỏ',
    resetZoomLabel: 'Đặt lại Zoom',
    zoomLevelLabel: 'Thu phóng',
    analysisResult: 'Kết Quả Phân Tích',

    confidence: 'Độ tin cậy',
    processingTime: 'Thời gian xử lý',
    detailScores: 'Tỉ lệ lỗi chi tiết',
    aiSurfaceDetection: 'Sử dụng AI để phát hiện lỗi bề mặt trong tích tắc.',
    perfectSurface: 'Bề mặt Hoàn hảo',
    anomalyDetected: 'Phát hiện Bất thường',
    perfectDesc: 'Không phát hiện thấy dấu hiệu hư hỏng hoặc lỗi bề mặt nào.',
    anomalyDesc: 'Hệ thống đã phát hiện các dấu hiệu không đồng nhất. Vui lòng kiểm tra lại.',

    // Inspect page
    inspectTitle: 'Kiểm Tra Ảnh',
    inspectSubtitle: 'Tải ảnh sản phẩm để phát hiện lỗi bằng AI',
    dropImageOrBrowse: 'Thả ảnh vào đây hoặc nhấn để chọn',
    dropHere: 'Thả vào đây',
    fileFormats: 'JPEG, PNG, WEBP · Tối đa 10MB',
    analyzeImage: '🔍 Phân Tích Ảnh',
    analyzing: 'Đang phân tích...',
    reset: 'Đặt Lại',
    resultsAppearHere: 'Kết quả phân tích sẽ hiển thị ở đây',
    runningAI: 'Đang chạy phân tích AI...',
    typicallyUnder: 'Thường mất dưới 200ms',
    noDefectsDetected: 'Không phát hiện lỗi',
    defectDetected: 'Phát hiện lỗi',
    scoreBreakdown: 'CHI TIẾT ĐIỂM SỐ',

    // Webcam
    useCamera: 'Dùng Camera',
    useUpload: 'Tải Tệp Lên',
    capture: 'Chụp & Phân Tích',
    retake: 'Chụp Lại',
    cameraError: 'Không thể truy cập Camera hoặc không tìm thấy thiết bị',

    // History page
    historyTitle: 'Lịch Sử Kiểm Tra',
    totalInspectionsLabel: 'tổng lần kiểm tra',
    loading: 'Đang tải...',
    file: 'Tệp',
    result: 'Kết Quả',
    speed: 'Tốc Độ',
    date: 'Ngày',
    prev: '← Trước',
    next: 'Tiếp →',
    page: 'Trang',
    of: 'của',
    noHistory: 'Chưa có lịch sử',
    noHistoryDesc: 'Thực hiện kiểm tra đầu tiên để xem kết quả tại đây',
    startInspecting: 'Bắt Đầu Kiểm Tra',

    // Usage page
    usageTitle: 'Sử Dụng & Gói',
    usageSubtitle: 'Quản lý gói đăng ký và theo dõi mức sử dụng',
    thisMonthsUsage: 'Sử Dụng Tháng Này',
    currentPlan: 'Gói Hiện Tại',
    unlimitedInspections: '✓ Không giới hạn kiểm tra',
    resetsOn: 'Làm mới vào',
    cancels: 'Hủy vào',
    renews: 'Gia hạn vào',
    cancelWarning: '⚠️ Gói của bạn sẽ bị hủy vào cuối kỳ thanh toán',
    upgradeBtnLabel: '⭐ Nâng Cấp Pro — $29/tháng',
    redirecting: 'Đang chuyển hướng...',
    cancelSubscription: 'Hủy Đăng Ký',
    canceling: 'Đang hủy...',
    remaining: 'còn lại',
    percentUsed: 'đã dùng',
    planComparison: 'So Sánh Gói',
    feature: 'Tính Năng',
    free: 'Miễn Phí',
    pro: 'Pro',
    planRows: [
      { feature: 'Kiểm tra / tháng', free: '50', pro: 'Không giới hạn' },
      { feature: 'Lưu lịch sử', free: '7 ngày', pro: '90 ngày' },
      { feature: 'Truy cập REST API', free: '✗', pro: '✓' },
      { feature: 'Hàng đợi ưu tiên', free: '✗', pro: '✓' },
      { feature: 'Hỗ trợ ưu tiên', free: '✗', pro: '✓' },
      { feature: 'Giá', free: '$0/tháng', pro: '$29/tháng' },
    ],
  },
} as const;

export type Translations = typeof translations.en | typeof translations.vi;

// ── Context ───────────────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: Lang;
  t: Translations;
  toggle: () => void;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'vi',
  t: translations.vi,
  toggle: () => {},
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('vi');
  const toggle = () => setLang((l) => (l === 'en' ? 'vi' : 'en'));

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export { translations };
